title: My Portfolio
theme: minima
description: "Welcome to my portfolio!"
url: "https://duartemfm.github.io"

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

#

author:
  name: Duarte Marques
  email: "duartemfmarques@gmail.com"
# Select which links to show in the footer
footer-links-active:
  email: true

